// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SpCoreProtoElements.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Z9.Spcore.Proto {

  /// <summary>Holder for reflection information generated from SpCoreProtoElements.proto</summary>
  public static partial class SpCoreProtoElementsReflection {

    #region Descriptor
    /// <summary>File descriptor for SpCoreProtoElements.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static SpCoreProtoElementsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChlTcENvcmVQcm90b0VsZW1lbnRzLnByb3RvEg96OS5zcGNvcmUucHJvdG8i",
            "KwoOQmlnSW50ZWdlckRhdGESDwoFYnl0ZXMYASABKAxIAEIICgZieXRlc18i",
            "WAoLU3FsRGF0ZURhdGESDgoEeWVhchgBIAEoBUgAEg8KBW1vbnRoGAIgASgF",
            "SAESDQoDZGF5GAMgASgFSAJCBwoFeWVhcl9CCAoGbW9udGhfQgYKBGRheV8i",
            "YAoLU3FsVGltZURhdGESDgoEaG91chgBIAEoBUgAEhAKBm1pbnV0ZRgCIAEo",
            "BUgBEhAKBnNlY29uZBgDIAEoBUgCQgcKBWhvdXJfQgkKB21pbnV0ZV9CCQoH",
            "c2Vjb25kXyIrCgxEYXRlVGltZURhdGESEAoGbWlsbGlzGAEgASgDSABCCQoH",
            "bWlsbGlzX0ICSANiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Z9.Spcore.Proto.BigIntegerData), global::Z9.Spcore.Proto.BigIntegerData.Parser, new[]{ "Bytes" }, new[]{ "Bytes" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Z9.Spcore.Proto.SqlDateData), global::Z9.Spcore.Proto.SqlDateData.Parser, new[]{ "Year", "Month", "Day" }, new[]{ "Year", "Month", "Day" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Z9.Spcore.Proto.SqlTimeData), global::Z9.Spcore.Proto.SqlTimeData.Parser, new[]{ "Hour", "Minute", "Second" }, new[]{ "Hour", "Minute", "Second" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Z9.Spcore.Proto.DateTimeData), global::Z9.Spcore.Proto.DateTimeData.Parser, new[]{ "Millis" }, new[]{ "Millis" }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class BigIntegerData : pb::IMessage<BigIntegerData> {
    private static readonly pb::MessageParser<BigIntegerData> _parser = new pb::MessageParser<BigIntegerData>(() => new BigIntegerData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BigIntegerData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Z9.Spcore.Proto.SpCoreProtoElementsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BigIntegerData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BigIntegerData(BigIntegerData other) : this() {
      switch (other.BytesCase) {
        case BytesOneofCase.Bytes:
          Bytes = other.Bytes;
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BigIntegerData Clone() {
      return new BigIntegerData(this);
    }

    /// <summary>Field number for the "bytes" field.</summary>
    public const int BytesFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Bytes {
      get { return bytesCase_ == BytesOneofCase.Bytes ? (pb::ByteString) bytes_ : pb::ByteString.Empty; }
      set {
        bytes_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        bytesCase_ = BytesOneofCase.Bytes;
      }
    }

    private object bytes_;
    /// <summary>Enum of possible cases for the "bytes_" oneof.</summary>
    public enum BytesOneofCase {
      None = 0,
      Bytes = 1,
    }
    private BytesOneofCase bytesCase_ = BytesOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BytesOneofCase BytesCase {
      get { return bytesCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearBytes() {
      bytesCase_ = BytesOneofCase.None;
      bytes_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BigIntegerData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BigIntegerData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Bytes != other.Bytes) return false;
      if (BytesCase != other.BytesCase) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (bytesCase_ == BytesOneofCase.Bytes) hash ^= Bytes.GetHashCode();
      hash ^= (int) bytesCase_;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (bytesCase_ == BytesOneofCase.Bytes) {
        output.WriteRawTag(10);
        output.WriteBytes(Bytes);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (bytesCase_ == BytesOneofCase.Bytes) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Bytes);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BigIntegerData other) {
      if (other == null) {
        return;
      }
      switch (other.BytesCase) {
        case BytesOneofCase.Bytes:
          Bytes = other.Bytes;
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            Bytes = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SqlDateData : pb::IMessage<SqlDateData> {
    private static readonly pb::MessageParser<SqlDateData> _parser = new pb::MessageParser<SqlDateData>(() => new SqlDateData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SqlDateData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Z9.Spcore.Proto.SpCoreProtoElementsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SqlDateData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SqlDateData(SqlDateData other) : this() {
      switch (other.YearCase) {
        case YearOneofCase.Year:
          Year = other.Year;
          break;
      }

      switch (other.MonthCase) {
        case MonthOneofCase.Month:
          Month = other.Month;
          break;
      }

      switch (other.DayCase) {
        case DayOneofCase.Day:
          Day = other.Day;
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SqlDateData Clone() {
      return new SqlDateData(this);
    }

    /// <summary>Field number for the "year" field.</summary>
    public const int YearFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Year {
      get { return yearCase_ == YearOneofCase.Year ? (int) year_ : 0; }
      set {
        year_ = value;
        yearCase_ = YearOneofCase.Year;
      }
    }

    /// <summary>Field number for the "month" field.</summary>
    public const int MonthFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Month {
      get { return monthCase_ == MonthOneofCase.Month ? (int) month_ : 0; }
      set {
        month_ = value;
        monthCase_ = MonthOneofCase.Month;
      }
    }

    /// <summary>Field number for the "day" field.</summary>
    public const int DayFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Day {
      get { return dayCase_ == DayOneofCase.Day ? (int) day_ : 0; }
      set {
        day_ = value;
        dayCase_ = DayOneofCase.Day;
      }
    }

    private object year_;
    /// <summary>Enum of possible cases for the "year_" oneof.</summary>
    public enum YearOneofCase {
      None = 0,
      Year = 1,
    }
    private YearOneofCase yearCase_ = YearOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public YearOneofCase YearCase {
      get { return yearCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearYear() {
      yearCase_ = YearOneofCase.None;
      year_ = null;
    }

    private object month_;
    /// <summary>Enum of possible cases for the "month_" oneof.</summary>
    public enum MonthOneofCase {
      None = 0,
      Month = 2,
    }
    private MonthOneofCase monthCase_ = MonthOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MonthOneofCase MonthCase {
      get { return monthCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMonth() {
      monthCase_ = MonthOneofCase.None;
      month_ = null;
    }

    private object day_;
    /// <summary>Enum of possible cases for the "day_" oneof.</summary>
    public enum DayOneofCase {
      None = 0,
      Day = 3,
    }
    private DayOneofCase dayCase_ = DayOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DayOneofCase DayCase {
      get { return dayCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearDay() {
      dayCase_ = DayOneofCase.None;
      day_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SqlDateData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SqlDateData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Year != other.Year) return false;
      if (Month != other.Month) return false;
      if (Day != other.Day) return false;
      if (YearCase != other.YearCase) return false;
      if (MonthCase != other.MonthCase) return false;
      if (DayCase != other.DayCase) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (yearCase_ == YearOneofCase.Year) hash ^= Year.GetHashCode();
      if (monthCase_ == MonthOneofCase.Month) hash ^= Month.GetHashCode();
      if (dayCase_ == DayOneofCase.Day) hash ^= Day.GetHashCode();
      hash ^= (int) yearCase_;
      hash ^= (int) monthCase_;
      hash ^= (int) dayCase_;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (yearCase_ == YearOneofCase.Year) {
        output.WriteRawTag(8);
        output.WriteInt32(Year);
      }
      if (monthCase_ == MonthOneofCase.Month) {
        output.WriteRawTag(16);
        output.WriteInt32(Month);
      }
      if (dayCase_ == DayOneofCase.Day) {
        output.WriteRawTag(24);
        output.WriteInt32(Day);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (yearCase_ == YearOneofCase.Year) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Year);
      }
      if (monthCase_ == MonthOneofCase.Month) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Month);
      }
      if (dayCase_ == DayOneofCase.Day) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Day);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SqlDateData other) {
      if (other == null) {
        return;
      }
      switch (other.YearCase) {
        case YearOneofCase.Year:
          Year = other.Year;
          break;
      }

      switch (other.MonthCase) {
        case MonthOneofCase.Month:
          Month = other.Month;
          break;
      }

      switch (other.DayCase) {
        case DayOneofCase.Day:
          Day = other.Day;
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Year = input.ReadInt32();
            break;
          }
          case 16: {
            Month = input.ReadInt32();
            break;
          }
          case 24: {
            Day = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SqlTimeData : pb::IMessage<SqlTimeData> {
    private static readonly pb::MessageParser<SqlTimeData> _parser = new pb::MessageParser<SqlTimeData>(() => new SqlTimeData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SqlTimeData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Z9.Spcore.Proto.SpCoreProtoElementsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SqlTimeData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SqlTimeData(SqlTimeData other) : this() {
      switch (other.HourCase) {
        case HourOneofCase.Hour:
          Hour = other.Hour;
          break;
      }

      switch (other.MinuteCase) {
        case MinuteOneofCase.Minute:
          Minute = other.Minute;
          break;
      }

      switch (other.SecondCase) {
        case SecondOneofCase.Second:
          Second = other.Second;
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SqlTimeData Clone() {
      return new SqlTimeData(this);
    }

    /// <summary>Field number for the "hour" field.</summary>
    public const int HourFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Hour {
      get { return hourCase_ == HourOneofCase.Hour ? (int) hour_ : 0; }
      set {
        hour_ = value;
        hourCase_ = HourOneofCase.Hour;
      }
    }

    /// <summary>Field number for the "minute" field.</summary>
    public const int MinuteFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Minute {
      get { return minuteCase_ == MinuteOneofCase.Minute ? (int) minute_ : 0; }
      set {
        minute_ = value;
        minuteCase_ = MinuteOneofCase.Minute;
      }
    }

    /// <summary>Field number for the "second" field.</summary>
    public const int SecondFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Second {
      get { return secondCase_ == SecondOneofCase.Second ? (int) second_ : 0; }
      set {
        second_ = value;
        secondCase_ = SecondOneofCase.Second;
      }
    }

    private object hour_;
    /// <summary>Enum of possible cases for the "hour_" oneof.</summary>
    public enum HourOneofCase {
      None = 0,
      Hour = 1,
    }
    private HourOneofCase hourCase_ = HourOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public HourOneofCase HourCase {
      get { return hourCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearHour() {
      hourCase_ = HourOneofCase.None;
      hour_ = null;
    }

    private object minute_;
    /// <summary>Enum of possible cases for the "minute_" oneof.</summary>
    public enum MinuteOneofCase {
      None = 0,
      Minute = 2,
    }
    private MinuteOneofCase minuteCase_ = MinuteOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MinuteOneofCase MinuteCase {
      get { return minuteCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMinute() {
      minuteCase_ = MinuteOneofCase.None;
      minute_ = null;
    }

    private object second_;
    /// <summary>Enum of possible cases for the "second_" oneof.</summary>
    public enum SecondOneofCase {
      None = 0,
      Second = 3,
    }
    private SecondOneofCase secondCase_ = SecondOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SecondOneofCase SecondCase {
      get { return secondCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearSecond() {
      secondCase_ = SecondOneofCase.None;
      second_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SqlTimeData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SqlTimeData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Hour != other.Hour) return false;
      if (Minute != other.Minute) return false;
      if (Second != other.Second) return false;
      if (HourCase != other.HourCase) return false;
      if (MinuteCase != other.MinuteCase) return false;
      if (SecondCase != other.SecondCase) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (hourCase_ == HourOneofCase.Hour) hash ^= Hour.GetHashCode();
      if (minuteCase_ == MinuteOneofCase.Minute) hash ^= Minute.GetHashCode();
      if (secondCase_ == SecondOneofCase.Second) hash ^= Second.GetHashCode();
      hash ^= (int) hourCase_;
      hash ^= (int) minuteCase_;
      hash ^= (int) secondCase_;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (hourCase_ == HourOneofCase.Hour) {
        output.WriteRawTag(8);
        output.WriteInt32(Hour);
      }
      if (minuteCase_ == MinuteOneofCase.Minute) {
        output.WriteRawTag(16);
        output.WriteInt32(Minute);
      }
      if (secondCase_ == SecondOneofCase.Second) {
        output.WriteRawTag(24);
        output.WriteInt32(Second);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (hourCase_ == HourOneofCase.Hour) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Hour);
      }
      if (minuteCase_ == MinuteOneofCase.Minute) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Minute);
      }
      if (secondCase_ == SecondOneofCase.Second) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Second);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SqlTimeData other) {
      if (other == null) {
        return;
      }
      switch (other.HourCase) {
        case HourOneofCase.Hour:
          Hour = other.Hour;
          break;
      }

      switch (other.MinuteCase) {
        case MinuteOneofCase.Minute:
          Minute = other.Minute;
          break;
      }

      switch (other.SecondCase) {
        case SecondOneofCase.Second:
          Second = other.Second;
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Hour = input.ReadInt32();
            break;
          }
          case 16: {
            Minute = input.ReadInt32();
            break;
          }
          case 24: {
            Second = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class DateTimeData : pb::IMessage<DateTimeData> {
    private static readonly pb::MessageParser<DateTimeData> _parser = new pb::MessageParser<DateTimeData>(() => new DateTimeData());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<DateTimeData> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Z9.Spcore.Proto.SpCoreProtoElementsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DateTimeData() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DateTimeData(DateTimeData other) : this() {
      switch (other.MillisCase) {
        case MillisOneofCase.Millis:
          Millis = other.Millis;
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public DateTimeData Clone() {
      return new DateTimeData(this);
    }

    /// <summary>Field number for the "millis" field.</summary>
    public const int MillisFieldNumber = 1;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Millis {
      get { return millisCase_ == MillisOneofCase.Millis ? (long) millis_ : 0L; }
      set {
        millis_ = value;
        millisCase_ = MillisOneofCase.Millis;
      }
    }

    private object millis_;
    /// <summary>Enum of possible cases for the "millis_" oneof.</summary>
    public enum MillisOneofCase {
      None = 0,
      Millis = 1,
    }
    private MillisOneofCase millisCase_ = MillisOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public MillisOneofCase MillisCase {
      get { return millisCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearMillis() {
      millisCase_ = MillisOneofCase.None;
      millis_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as DateTimeData);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(DateTimeData other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Millis != other.Millis) return false;
      if (MillisCase != other.MillisCase) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (millisCase_ == MillisOneofCase.Millis) hash ^= Millis.GetHashCode();
      hash ^= (int) millisCase_;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (millisCase_ == MillisOneofCase.Millis) {
        output.WriteRawTag(8);
        output.WriteInt64(Millis);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (millisCase_ == MillisOneofCase.Millis) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Millis);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(DateTimeData other) {
      if (other == null) {
        return;
      }
      switch (other.MillisCase) {
        case MillisOneofCase.Millis:
          Millis = other.Millis;
          break;
      }

    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            Millis = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
